# Generated by Django 4.2.4 on 2023-08-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='quantity',
        ),
    ]
