# Generated by Django 4.2.4 on 2023-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_remove_cart_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rent_date',
            field=models.DateField(default='2023-08-12'),
            preserve_default=False,
        ),
    ]
