# Generated by Django 4.2.4 on 2023-08-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_house_rent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bathroom_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='bedroom_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='flat_size',
            field=models.IntegerField(default=222),
            preserve_default=False,
        ),
    ]
