# Generated by Django 4.2.4 on 2023-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Family', 'Family'), ('Bachelor', 'Bachelor'), ('Sublet', 'Sublet')], default='Family', max_length=10),
        ),
    ]
