# Generated by Django 4.2.4 on 2023-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_alter_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='gender',
            field=models.TextField(default='Any'),
        ),
    ]
