# Generated by Django 4.2.4 on 2023-08-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_house_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='gender',
            field=models.TextField(default='Both'),
        ),
    ]
