# Generated by Django 4.2.4 on 2023-08-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_alter_house_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price2', models.DecimalField(decimal_places=2, default=10000000000000, max_digits=10)),
                ('location', models.TextField(default='')),
                ('gender', models.TextField(default='')),
                ('type', models.CharField(choices=[('family', 'Family'), ('bachelor', 'Bachelor'), ('sublet', 'Sublet')], default=None, max_length=10)),
            ],
        ),
    ]
