# Generated by Django 4.2.4 on 2023-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0010_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='gender',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='price1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=99999999.99, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='type',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('bachelor', 'Bachelor'), ('sublet', 'Sublet')], default=None, max_length=10, null=True),
        ),
    ]
