# Generated by Django 4.2.4 on 2023-08-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0011_alter_search_gender_alter_search_price1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='price1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
