# Generated by Django 4.2.4 on 2023-08-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0012_alter_search_price1_alter_search_price2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='location',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
